aliases:
  - &filter-only-master
    branches:
      only:
        - master


version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "sotarok@users.noreply.github.com"
            git config --global user.name "sotarok"
            echo "machine github.com login sotarok password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=<GIT_USER> yarn run publish-gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-master
