aliases:
  - &filter-only-master
    branches:
      only:
        - master


version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1
    branches:
      ignore: gh-pages

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "crowi-docs-bot@users.noreply.github.com"
            git config --global user.name "Crowi Docs Bot"
            echo "machine github.com login sotarok password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=sotarok yarn run publish-gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-master
